const obj = {
  id: "",
  nickname: "",
  profilepic: "",
  seen_count: 0,
  is_active: false,
  purpose: "",
  interested_in: "",
  about: "<div>Tell people about you..</div>",
  report_count: 0,
  gender: "Male",
  star_sign: "",
  age: 0,
  sexual_orientation: "",
  university: "",
  location: "",
  show_me: ["Female", "Male"],
  g_postion: "",
  hashed_location: "",
  is_online: false,
  alt: "",
  long: "",
  parentID: "",
  show_sorientation: false,
  yearOfStudy: "1st",
  blocked: [],
};

export default obj;
